services:
  iahx_controller:
    container_name: iahx-controller
    build:
      context: .
      target: prod
    restart: unless-stopped
    env_file:
      '.env'
    volumes:
      - redis_data:/redis_data
    ports:
      - 8000:8000
    networks:
      - nginx-proxy

  iahx_controller_cache:
    image: bitnami/redis:7.2
    container_name: iahx-controller-cache
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
      - TZ=${TIMEZONE}
    volumes:
      - redis_data:/bitnami/redis/data
    command:  /opt/bitnami/scripts/redis/run.sh --maxmemory ${APP_CACHE_MEMORY} --maxmemory-policy allkeys-lru
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
      external: true

volumes:
  redis_data: